on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  - cron: 19 11 * * *
name: Semgrep
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
    - name: Download Xygeni Scanner 
        run: |
          echo xxxxxxxx ....
          mvn dependency:tree -DoutputFile=maven_dep_tree.txt
          mvn clean package
          ls -l maven_dep_tree.txt
          exit 1
    - uses: actions/checkout@v4
    - run: semgrep ci
